# Generated by Django 5.1.3 on 2024-11-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('nameofchild', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('yob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'other')], max_length=19)),
                ('phonenumber', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('nameofparent', models.CharField(max_length=250)),
                ('admissionno', models.CharField(max_length=15, unique=True)),
                ('photo', models.ImageField(upload_to='')),
                ('gradelevel', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('yob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'other')], max_length=19)),
                ('address', models.CharField(max_length=50)),
                ('joindate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('yob', models.DateField()),
                ('payrollno', models.CharField(max_length=15, unique=True)),
                ('hiredate', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='')),
                ('subjects', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'other')], max_length=19)),
                ('address', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=4, max_digits=14)),
                ('experience', models.CharField(max_length=400)),
            ],
        ),
    ]
