# Generated by Django 5.1.3 on 2024-11-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amberleafapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfStudent', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('nameofParent', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('dateOfInterview', models.DateField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='hiredate',
            new_name='hireDate',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='payrollno',
            new_name='payrollNo',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='phonenumber',
            new_name='phoneNumber',
        ),
    ]
