# Generated by Django 5.1.3 on 2024-11-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amberleafapp', '0002_interview_rename_hiredate_teacher_hiredate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='dateOfInterview',
            new_name='date_of_interview',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='nameOfStudent',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='nameofParent',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='interview',
            name='name_of_parent',
            field=models.CharField(default='Default Name', max_length=255),
        ),
        migrations.AddField(
            model_name='interview',
            name='name_of_student',
            field=models.CharField(default='Default Name', max_length=255),
        ),
        migrations.AddField(
            model_name='interview',
            name='phone_number',
            field=models.CharField(default='Default Phone Number', max_length=15),
        ),
        migrations.AlterField(
            model_name='interview',
            name='grade',
            field=models.CharField(max_length=50),
        ),
    ]
