# Generated by Django 5.1.3 on 2024-12-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amberleafapp', '0003_rename_dateofinterview_interview_date_of_interview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
