# Generated by Django 5.1.3 on 2024-12-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amberleafapp', '0005_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('parent_phone', models.CharField(max_length=15)),
                ('pickup_time', models.TimeField()),
            ],
        ),
    ]
