# Generated by Django 5.1.3 on 2024-12-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amberleafapp', '0006_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwimmingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Student Name')),
                ('grade', models.CharField(max_length=50, verbose_name='Grade')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='Gender')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Booking Date')),
            ],
        ),
    ]
