# Generated by Django 5.1.3 on 2024-12-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amberleafapp', '0008_skatebooking_yogabooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoneTeaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('yob', models.DateField()),
                ('payrollNo', models.CharField(max_length=15, unique=True)),
                ('hireDate', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'other')], max_length=19)),
                ('address', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=4, max_digits=14)),
            ],
        ),
    ]
