# Generated by Django 5.1.3 on 2024-12-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amberleafapp', '0009_noneteaching'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDirectorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=50)),
                ('n', models.CharField(max_length=50)),
            ],
        ),
    ]
