# Generated by Django 5.1.3 on 2024-12-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amberleafapp', '0010_imagedirectormodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedirectormodel',
            name='n',
        ),
        migrations.AddField(
            model_name='imagedirectormodel',
            name='narration',
            field=models.CharField(blank=True, default='Default narration text', max_length=500),
        ),
    ]
