# Generated by Django 5.1.3 on 2024-12-07 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amberleafapp', '0012_imagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='price',
            new_name='essay',
        ),
    ]
